# Generated by Django 4.1.1 on 2022-10-07 16:44

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicio', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=70)),
                ('telefono', models.CharField(max_length=12)),
                ('fecha_de_alta', models.DateField()),
                ('usuario', models.CharField(max_length=255)),
                ('suscripcion', models.BooleanField()),
                ('plan', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='servicio', chained_model_field='servicio', null=True, on_delete=django.db.models.deletion.CASCADE, to='servicio.plan')),
                ('servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicio.servicio')),
            ],
        ),
    ]
