# Generated by Django 4.1.1 on 2022-09-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='register',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
