# Generated by Django 4.1.1 on 2022-10-03 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
        ('clientes', '0002_suscripcion_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicio.plan'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicio.servicio'),
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
