# Generated by Django 4.1.1 on 2022-10-03 16:43

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
        ('clientes', '0003_cliente_plan_cliente_servicio_delete_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='plan',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='servicio', chained_model_field='servicio', null=True, on_delete=django.db.models.deletion.CASCADE, to='servicio.plan'),
        ),
    ]
