# Generated by Django 4.1.1 on 2022-10-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='saldo',
            field=models.IntegerField(null=True),
        ),
    ]
