# Generated by Django 4.1.1 on 2022-10-21 23:12

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('periodo', '0001_initial'),
        ('pagos', '0002_pagos_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='periodo',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='servicio', chained_model_field='servicio', null=True, on_delete=django.db.models.deletion.CASCADE, to='periodo.periodo'),
        ),
    ]
