# Generated by Django 4.1.1 on 2022-10-21 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('periodo', '0001_initial'),
        ('pagos', '0003_alter_pagos_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='periodo.periodo'),
        ),
    ]
